# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(679, 449)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 671, 411))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 261, 221))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.pushButton_5 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_5.setGeometry(QtCore.QRect(170, 180, 81, 23))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.listWidget = QtGui.QListWidget(self.groupBox_2)
        self.listWidget.setGeometry(QtCore.QRect(10, 40, 151, 161))
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 240, 261, 141))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.textEdit = QtGui.QTextEdit(self.groupBox)
        self.textEdit.setGeometry(QtCore.QRect(20, 20, 151, 31))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.textEdit_2 = QtGui.QTextEdit(self.groupBox)
        self.textEdit_2.setGeometry(QtCore.QRect(20, 60, 151, 31))
        self.textEdit_2.setObjectName(_fromUtf8("textEdit_2"))
        self.pushButton = QtGui.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(180, 20, 75, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 60, 75, 23))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(280, 20, 171, 141))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.checkBox = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox.setGeometry(QtCore.QRect(20, 30, 131, 17))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.comboBox_2 = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_2.setGeometry(QtCore.QRect(20, 80, 131, 22))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.label_6 = QtGui.QLabel(self.groupBox_4)
        self.label_6.setGeometry(QtCore.QRect(20, 60, 91, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab)
        self.groupBox_6.setGeometry(QtCore.QRect(460, 20, 191, 141))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.comboBox_4 = QtGui.QComboBox(self.groupBox_6)
        self.comboBox_4.setGeometry(QtCore.QRect(10, 40, 131, 22))
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.label_11 = QtGui.QLabel(self.groupBox_6)
        self.label_11.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.pushButton_6 = QtGui.QPushButton(self.tab)
        self.pushButton_6.setGeometry(QtCore.QRect(280, 340, 101, 31))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.tab)
        self.doubleSpinBox.setGeometry(QtCore.QRect(300, 190, 62, 22))
        self.doubleSpinBox.setMaximum(1.0)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.label_26 = QtGui.QLabel(self.tab)
        self.label_26.setGeometry(QtCore.QRect(290, 170, 81, 20))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.Temp_button = QtGui.QPushButton(self.tab)
        self.Temp_button.setGeometry(QtCore.QRect(500, 190, 151, 23))
        self.Temp_button.setObjectName(_fromUtf8("Temp_button"))
        self.Temp_button_2 = QtGui.QPushButton(self.tab)
        self.Temp_button_2.setGeometry(QtCore.QRect(500, 220, 151, 23))
        self.Temp_button_2.setObjectName(_fromUtf8("Temp_button_2"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.groupBox_7 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 10, 271, 181))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.pushButton_4 = QtGui.QPushButton(self.groupBox_7)
        self.pushButton_4.setEnabled(True)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 150, 81, 23))
        self.pushButton_4.setCheckable(False)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.label_13 = QtGui.QLabel(self.groupBox_7)
        self.label_13.setGeometry(QtCore.QRect(160, 50, 21, 20))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.groupBox_7)
        self.label_14.setGeometry(QtCore.QRect(160, 110, 21, 20))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.groupBox_7)
        self.label_15.setGeometry(QtCore.QRect(10, 50, 61, 20))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.groupBox_7)
        self.label_16.setGeometry(QtCore.QRect(10, 110, 61, 20))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.groupBox_7)
        self.label_17.setGeometry(QtCore.QRect(120, 150, 51, 20))
        self.label_17.setText(_fromUtf8(""))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.spinBox = QtGui.QSpinBox(self.groupBox_7)
        self.spinBox.setGeometry(QtCore.QRect(70, 50, 42, 22))
        self.spinBox.setMaximum(23)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.spinBox_2 = QtGui.QSpinBox(self.groupBox_7)
        self.spinBox_2.setGeometry(QtCore.QRect(110, 50, 42, 22))
        self.spinBox_2.setMaximum(59)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.spinBox_3 = QtGui.QSpinBox(self.groupBox_7)
        self.spinBox_3.setGeometry(QtCore.QRect(220, 50, 42, 22))
        self.spinBox_3.setMaximum(59)
        self.spinBox_3.setObjectName(_fromUtf8("spinBox_3"))
        self.spinBox_4 = QtGui.QSpinBox(self.groupBox_7)
        self.spinBox_4.setGeometry(QtCore.QRect(180, 50, 42, 22))
        self.spinBox_4.setMaximum(23)
        self.spinBox_4.setObjectName(_fromUtf8("spinBox_4"))
        self.spinBox_5 = QtGui.QSpinBox(self.groupBox_7)
        self.spinBox_5.setGeometry(QtCore.QRect(180, 110, 42, 22))
        self.spinBox_5.setMaximum(23)
        self.spinBox_5.setObjectName(_fromUtf8("spinBox_5"))
        self.spinBox_6 = QtGui.QSpinBox(self.groupBox_7)
        self.spinBox_6.setGeometry(QtCore.QRect(110, 110, 42, 22))
        self.spinBox_6.setMaximum(59)
        self.spinBox_6.setObjectName(_fromUtf8("spinBox_6"))
        self.spinBox_7 = QtGui.QSpinBox(self.groupBox_7)
        self.spinBox_7.setGeometry(QtCore.QRect(220, 110, 42, 22))
        self.spinBox_7.setMaximum(59)
        self.spinBox_7.setObjectName(_fromUtf8("spinBox_7"))
        self.spinBox_8 = QtGui.QSpinBox(self.groupBox_7)
        self.spinBox_8.setGeometry(QtCore.QRect(70, 110, 42, 22))
        self.spinBox_8.setMaximum(23)
        self.spinBox_8.setObjectName(_fromUtf8("spinBox_8"))
        self.label_18 = QtGui.QLabel(self.groupBox_7)
        self.label_18.setGeometry(QtCore.QRect(80, 80, 46, 13))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_19 = QtGui.QLabel(self.groupBox_7)
        self.label_19.setGeometry(QtCore.QRect(190, 80, 46, 13))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.groupBox_7)
        self.label_20.setGeometry(QtCore.QRect(80, 130, 46, 13))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.groupBox_7)
        self.label_21.setGeometry(QtCore.QRect(190, 130, 46, 13))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(self.groupBox_7)
        self.label_22.setGeometry(QtCore.QRect(120, 80, 46, 13))
        self.label_22.setFrameShadow(QtGui.QFrame.Plain)
        self.label_22.setLineWidth(0)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_23 = QtGui.QLabel(self.groupBox_7)
        self.label_23.setGeometry(QtCore.QRect(230, 80, 46, 13))
        self.label_23.setFrameShadow(QtGui.QFrame.Plain)
        self.label_23.setLineWidth(0)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(self.groupBox_7)
        self.label_24.setGeometry(QtCore.QRect(230, 130, 46, 13))
        self.label_24.setFrameShadow(QtGui.QFrame.Plain)
        self.label_24.setLineWidth(0)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_25 = QtGui.QLabel(self.groupBox_7)
        self.label_25.setGeometry(QtCore.QRect(120, 130, 46, 13))
        self.label_25.setFrameShadow(QtGui.QFrame.Plain)
        self.label_25.setLineWidth(0)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.pushButton_11 = QtGui.QPushButton(self.groupBox_7)
        self.pushButton_11.setGeometry(QtCore.QRect(80, 20, 121, 21))
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.pushButton_12 = QtGui.QPushButton(self.groupBox_7)
        self.pushButton_12.setEnabled(True)
        self.pushButton_12.setGeometry(QtCore.QRect(160, 150, 91, 23))
        self.pushButton_12.setCheckable(False)
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.groupBox_8 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_8.setGeometry(QtCore.QRect(300, 20, 351, 111))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.pushButton_8 = QtGui.QPushButton(self.groupBox_8)
        self.pushButton_8.setGeometry(QtCore.QRect(20, 30, 101, 23))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.pushButton_9 = QtGui.QPushButton(self.groupBox_8)
        self.pushButton_9.setGeometry(QtCore.QRect(20, 70, 101, 23))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.textEdit_3 = QtGui.QTextEdit(self.groupBox_8)
        self.textEdit_3.setGeometry(QtCore.QRect(130, 30, 211, 31))
        self.textEdit_3.setObjectName(_fromUtf8("textEdit_3"))
        self.textEdit_4 = QtGui.QTextEdit(self.groupBox_8)
        self.textEdit_4.setGeometry(QtCore.QRect(130, 70, 211, 31))
        self.textEdit_4.setObjectName(_fromUtf8("textEdit_4"))
        self.groupBox_9 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 200, 261, 171))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.textEdit_5 = QtGui.QTextEdit(self.groupBox_9)
        self.textEdit_5.setGeometry(QtCore.QRect(20, 20, 231, 31))
        self.textEdit_5.setObjectName(_fromUtf8("textEdit_5"))
        self.textEdit_6 = QtGui.QTextEdit(self.groupBox_9)
        self.textEdit_6.setGeometry(QtCore.QRect(20, 60, 231, 31))
        self.textEdit_6.setObjectName(_fromUtf8("textEdit_6"))
        self.pushButton_10 = QtGui.QPushButton(self.groupBox_9)
        self.pushButton_10.setGeometry(QtCore.QRect(90, 100, 75, 23))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.groupBox_10 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_10.setGeometry(QtCore.QRect(290, 140, 361, 231))
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.pushButton_7 = QtGui.QPushButton(self.groupBox_10)
        self.pushButton_7.setGeometry(QtCore.QRect(270, 200, 81, 23))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.label_27 = QtGui.QLabel(self.groupBox_10)
        self.label_27.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.listWidget_2 = QtGui.QListWidget(self.groupBox_10)
        self.listWidget_2.setGeometry(QtCore.QRect(10, 40, 151, 181))
        self.listWidget_2.setObjectName(_fromUtf8("listWidget_2"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 10, 651, 341))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.tableWidget = QtGui.QTableWidget(self.groupBox_3)
        self.tableWidget.setGeometry(QtCore.QRect(10, 70, 201, 261))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.comboBox = QtGui.QComboBox(self.groupBox_3)
        self.comboBox.setGeometry(QtCore.QRect(490, 20, 121, 22))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(400, 20, 81, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.tableWidget_2 = QtGui.QTableWidget(self.groupBox_3)
        self.tableWidget_2.setGeometry(QtCore.QRect(220, 70, 211, 261))
        self.tableWidget_2.setObjectName(_fromUtf8("tableWidget_2"))
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.tableWidget_3 = QtGui.QTableWidget(self.groupBox_3)
        self.tableWidget_3.setGeometry(QtCore.QRect(435, 70, 201, 261))
        self.tableWidget_3.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget_3.setObjectName(_fromUtf8("tableWidget_3"))
        self.tableWidget_3.setColumnCount(0)
        self.tableWidget_3.setRowCount(0)
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(90, 50, 46, 13))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(310, 50, 46, 13))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(510, 50, 51, 20))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.pushButton_lff = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_lff.setGeometry(QtCore.QRect(10, 20, 75, 23))
        self.pushButton_lff.setObjectName(_fromUtf8("pushButton_lff"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_5.setGeometry(QtCore.QRect(0, 10, 651, 341))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.tableWidget_4 = QtGui.QTableWidget(self.groupBox_5)
        self.tableWidget_4.setGeometry(QtCore.QRect(10, 70, 201, 261))
        self.tableWidget_4.setObjectName(_fromUtf8("tableWidget_4"))
        self.tableWidget_4.setColumnCount(0)
        self.tableWidget_4.setRowCount(0)
        self.comboBox_3 = QtGui.QComboBox(self.groupBox_5)
        self.comboBox_3.setGeometry(QtCore.QRect(490, 20, 121, 22))
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.label_7 = QtGui.QLabel(self.groupBox_5)
        self.label_7.setGeometry(QtCore.QRect(400, 20, 81, 20))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.tableWidget_5 = QtGui.QTableWidget(self.groupBox_5)
        self.tableWidget_5.setGeometry(QtCore.QRect(220, 70, 211, 261))
        self.tableWidget_5.setObjectName(_fromUtf8("tableWidget_5"))
        self.tableWidget_5.setColumnCount(0)
        self.tableWidget_5.setRowCount(0)
        self.tableWidget_6 = QtGui.QTableWidget(self.groupBox_5)
        self.tableWidget_6.setGeometry(QtCore.QRect(435, 70, 201, 261))
        self.tableWidget_6.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget_6.setObjectName(_fromUtf8("tableWidget_6"))
        self.tableWidget_6.setColumnCount(0)
        self.tableWidget_6.setRowCount(0)
        self.label_8 = QtGui.QLabel(self.groupBox_5)
        self.label_8.setGeometry(QtCore.QRect(90, 50, 46, 13))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.groupBox_5)
        self.label_9.setGeometry(QtCore.QRect(310, 50, 46, 13))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.groupBox_5)
        self.label_10.setGeometry(QtCore.QRect(510, 50, 51, 20))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.pushButton_lff_2 = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_lff_2.setGeometry(QtCore.QRect(10, 20, 75, 23))
        self.pushButton_lff_2.setObjectName(_fromUtf8("pushButton_lff_2"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.pushButton_13 = QtGui.QPushButton(self.tab_5)
        self.pushButton_13.setGeometry(QtCore.QRect(280, 160, 75, 23))
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.pushButton_14 = QtGui.QPushButton(self.tab_5)
        self.pushButton_14.setGeometry(QtCore.QRect(580, 350, 75, 23))
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(310, 410, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.pushButton_3 = QtGui.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(160, 420, 291, 21))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Base CDR\'s", None))
        self.pushButton_5.setText(_translate("Dialog", "Choose CDR\'s", None))
        self.label.setText(_translate("Dialog", "Detected Users", None))
        self.groupBox.setTitle(_translate("Dialog", "Select Home/Work Localization", None))
        self.pushButton.setText(_translate("Dialog", "Select Home", None))
        self.pushButton_2.setText(_translate("Dialog", "Select Work", None))
        self.groupBox_4.setTitle(_translate("Dialog", "Options", None))
        self.checkBox.setText(_translate("Dialog", "Different on weekends", None))
        self.label_6.setText(_translate("Dialog", "Movement mode", None))
        self.groupBox_6.setTitle(_translate("Dialog", "Time Resoultion", None))
        self.label_11.setText(_translate("Dialog", "Time aggregation", None))
        self.pushButton_6.setText(_translate("Dialog", "Load Antenas/Grid", None))
        self.label_26.setText(_translate("Dialog", "Activity Spread", None))
        self.Temp_button.setText(_translate("Dialog", "Generate from positions file", None))
        self.Temp_button_2.setText(_translate("Dialog", "WHERE2", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Create", None))
        self.groupBox_7.setTitle(_translate("Dialog", "Calculate Home/Work Localization", None))
        self.pushButton_4.setText(_translate("Dialog", "Load Track File", None))
        self.label_13.setText(_translate("Dialog", "to", None))
        self.label_14.setText(_translate("Dialog", "to", None))
        self.label_15.setText(_translate("Dialog", "Home Time", None))
        self.label_16.setText(_translate("Dialog", "Work Time", None))
        self.label_18.setText(_translate("Dialog", "H", None))
        self.label_19.setText(_translate("Dialog", "H", None))
        self.label_20.setText(_translate("Dialog", "H", None))
        self.label_21.setText(_translate("Dialog", "H", None))
        self.label_22.setText(_translate("Dialog", "m", None))
        self.label_23.setText(_translate("Dialog", "m", None))
        self.label_24.setText(_translate("Dialog", "m", None))
        self.label_25.setText(_translate("Dialog", "m", None))
        self.pushButton_11.setText(_translate("Dialog", "Load Aggregation Grid", None))
        self.pushButton_12.setText(_translate("Dialog", "Load Census File", None))
        self.groupBox_8.setTitle(_translate("Dialog", "Home/Work Probability Layers", None))
        self.pushButton_8.setText(_translate("Dialog", "Load home layer", None))
        self.pushButton_9.setText(_translate("Dialog", "Load work layer", None))
        self.groupBox_9.setTitle(_translate("Dialog", "Random Home/Work Localization", None))
        self.pushButton_10.setText(_translate("Dialog", "Randomize", None))
        self.groupBox_10.setTitle(_translate("Dialog", "Base CDR\'s", None))
        self.pushButton_7.setText(_translate("Dialog", "Choose CDR\'s", None))
        self.label_27.setText(_translate("Dialog", "Detected Users", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "Generate", None))
        self.groupBox_3.setTitle(_translate("Dialog", "Probabilities", None))
        self.label_2.setText(_translate("Dialog", "Choose Profile", None))
        self.label_3.setText(_translate("Dialog", "Home", None))
        self.label_4.setText(_translate("Dialog", "Work", None))
        self.label_5.setText(_translate("Dialog", "Third Place", None))
        self.pushButton_lff.setText(_translate("Dialog", "Load from file", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Normal Probabilities", None))
        self.groupBox_5.setTitle(_translate("Dialog", "Weekend probabilities", None))
        self.label_7.setText(_translate("Dialog", "Choose Profile", None))
        self.label_8.setText(_translate("Dialog", "Home", None))
        self.label_9.setText(_translate("Dialog", "Work", None))
        self.label_10.setText(_translate("Dialog", "Third Place", None))
        self.pushButton_lff_2.setText(_translate("Dialog", "Load from file", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Weekend Probabilities", None))
        self.pushButton_13.setText(_translate("Dialog", "Calculate", None))
        self.pushButton_14.setText(_translate("Dialog", "Tempy", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Dialog", "Statistical", None))
        self.pushButton_3.setText(_translate("Dialog", "Generate", None))

